[default.extend-words]
sur = "sur" # french
Serie = "Serie" # french

[files]
extend-exclude = [
"tutorials/*.html",
# rendered from tutorials/*.qmd -Z we do not want typos twice
"docs/src/tutorials/*.md",
"joss/paper.md",
]