[default.extend-words]
methodes = "methodes" # french
Serie = "Serie" # french
sur = "sur" # french
cmo = "cmo" # often ussed abbreciation for constrained manifold objective

[files]
extend-exclude = [
"tutorials/*.html",
# rendered from tutorials/*.qmd -Z we do not want typos twice
"docs/src/tutorials/*.md",
"joss/paper.md",
]