[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
ManifoldDiff = "af67fdf4-a580-4b9f-bbec-742ef357defd"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
ManifoldsBase = "3362f125-f0bb-47a3-aa74-596ffd7ef2fb"
Manopt = "0fc0a36d-df90-57f3-8f93-d78a9fc72bb5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"

[compat]
BenchmarkTools = "1"
Colors = "0.12, 0.13"
Distributions = "0.25"
FiniteDifferences = "0.12"
IJulia = "1"
LRUCache = "1.4"
ManifoldDiff = "0.3.9"
Manifolds = "0.8.81, 0.9, 0.10"
ManifoldsBase = "0.14.12, 0.15"
Manopt = "0.5"
Plots = "1.38"
RecursiveArrayTools = "2, 3"
